// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-modules.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var modules = [
  { id: "normativa", title: "Cumplimiento normativo \xB7 SILICIE autom\xE1tico", description: "SILICIE, INFOVI, libros JCYL y alertas de rendimiento/mermas." },
  { id: "costes", title: "Control de costes", description: "Coste por litro, por dep\xF3sito y por botella con desglose completo." },
  { id: "campo", title: "Campo y vi\xF1edo", description: "Parcelas SIGPAC, cuaderno de campo digital (RD 1311/2012), fitosanitarios, fenolog\xEDa, ecol\xF3gico (Reg. UE 2018/848)." },
  { id: "vendimia", title: "Vendimia", description: "Entradas de uva por viticultor con trazabilidad parcela \u2192 dep\xF3sito \u2192 lote \u2192 botella." },
  { id: "bodega", title: "Bodega", description: "Dep\xF3sitos y barricas con QR, movimientos, cat\xE1logo de vinos con c\xF3digo NC." },
  { id: "laboratorio", title: "Laboratorio", description: "Anal\xEDticas completas, seguimiento de fermentaci\xF3n y alertas." },
  { id: "embotellado", title: "Embotellado y etiquetado", description: "Lotes, descuento autom\xE1tico de materiales, e-label (Reg. UE 2021/2117)." },
  { id: "expediciones", title: "Expediciones", description: "Albaranes nacionales, EMCS intracomunitario y exportaci\xF3n." },
  { id: "rrhh", title: "Recursos humanos", description: "Control horario (RD-ley 8/2019), partes de trabajo, carnets ROPO." },
  { id: "proveedores", title: "Proveedores", description: "Ficha centralizada con condiciones de pago." }
];
var list_modules_default = defineTool({
  name: "list_modules",
  title: "Listar m\xF3dulos de Datuva",
  description: "Devuelve la lista de m\xF3dulos funcionales del software vitivin\xEDcola Datuva con id, t\xEDtulo y descripci\xF3n breve.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(modules, null, 2) }],
    structuredContent: { modules }
  })
});

// src/lib/mcp/tools/get-module.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var get_module_default = defineTool2({
  name: "get_module",
  title: "Detalle de un m\xF3dulo",
  description: "Devuelve el detalle de un m\xF3dulo concreto de Datuva por su id.",
  inputSchema: {
    id: z.string().describe("Identificador del m\xF3dulo (p. ej. 'normativa', 'campo', 'bodega').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const found = modules.find((m) => m.id === id);
    if (!found) {
      return { content: [{ type: "text", text: `M\xF3dulo no encontrado: ${id}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(found, null, 2) }],
      structuredContent: found
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_contact_default = defineTool3({
  name: "get_contact",
  title: "Datos de contacto de Datuva",
  description: "Devuelve los canales oficiales de contacto para solicitar demo o informaci\xF3n comercial de Datuva.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      name: "Manuel Moreira",
      email: "manuelmoreira@datuva.es",
      whatsapp: "+34 627 130 891",
      website: "https://datuva.es"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "datuva-mcp",
  title: "Datuva MCP",
  version: "0.1.0",
  instructions: "Servidor MCP de Datuva, software integral de gesti\xF3n vitivin\xEDcola. Usa list_modules para descubrir las \xE1reas funcionales (cumplimiento SILICIE/INFOVI, campo, vendimia, bodega, laboratorio, embotellado, expediciones, RRHH, costes y proveedores), get_module para el detalle de un m\xF3dulo concreto y get_contact para los canales oficiales de contacto comercial.",
  tools: [list_modules_default, get_module_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
